version: '3.4'

services:
  webgoatnet:
    image: ${DOCKER_REGISTRY-}webgoatnet
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./contrast_security.yaml:/app/contrast_security.yaml
    environment:
      - CORECLR_PROFILER_PATH_64=/app/contrast/runtimes/linux-x64/native/ContrastProfiler.so
      - CORECLR_PROFILER={8B2CE134-0948-48CA-A4B2-80DDAD9F5791}
      - CORECLR_ENABLE_PROFILING=1
      - CONTRAST_CONFIG_PATH=/app/contrast_security.yaml
    ports:
      - "5004:80"
